spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource_manager?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # Para desarrollo; en producción evalúa otras opciones
      ddl-auto: update   
    # Para ver las consultas SQL ejecutadas
    show-sql: true       
